services:
  postgres:
    image: postgres:16
    container_name: marketplace-postgres
    environment:
      POSTGRES_DB: MarketPlaceApi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: marketplace-api
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=MarketPlaceApi;Username=postgres;Password=postgres
    ports:
      - "5001:8080"

volumes:
  pgdata:
